#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export CLIENT_OS=centos7
export CLIENT_HOSTNAME=hirs-client-$CLIENT_OS-tpm2

export SERVER_OS=$CLIENT_OS
export SERVER_HOSTNAME=hirs-appraiser-$SERVER_OS

export ENABLED_COLLECTORS=
export TPM_VERSION=2.0

#echo "CLIENT_OS = ${CLIENT_OS}"
#echo "CLIENT_HOSTNAME = ${CLIENT_HOSTNAME}"
#echo "SERVER_OS = ${SERVER_OS}"
#echo "SERVER_HOSTNAME  = ${SERVER_HOSTNAME}"
#echo "ENABLED_COLLECTORS = ${ENABLED_COLLECTORS}"
#echo "TPM_VERSION = ${TPM_VERSION}"

#echo "Values from Docker .env file: "
#echo "HIRS_SUBNET=${HIRS_SUBNET}"
#echo "HIRS_ACA_PORTAL_IP=${HIRS_ACA_PORTAL_IP}"
#echo "HIRS_ACA_PORTAL_PORT=${HIRS_ACA_PORTAL_PORT}"
#echo "HIRS_ACA_PORTAL_CONTAINER_PORT=${HIRS_ACA_PORTAL_CONTAINER_PORT}"
#echo "HIRS_BROKER_PORT=${HIRS_BROKER_PORT}"
#echo "HIRS_ACA_PROVISIONER_IP=${HIRS_ACA_PROVISIONER_IP}"
#echo "TPM_ENABLED=${TPM_ENABLED}"
#echo "IMA_ENABLED=${IMA_ENABLED}"

$SCRIPT_DIR/systems-test.core.sh