version: "3.1"
services:
  aca:
    image: hirs/hirs-ci:aca
    ports:
      - "8443:8443"
    volumes:
      - ../../:/HIRS
    command: /HIRS/.ci/integration-tests/setup-aca.sh
  tpm2provisioner:
    image: hirs/hirs-ci:tpm2provisioner
    depends_on:
      - "aca"
    volumes:
      - ../../:/HIRS
    network_mode: "host"
    command: /HIRS/.ci/integration-tests/setup-tpm2provisioner.sh
